// Generated by CoffeeScript 1.7.1
(function() {
  var StormAgent, agent, argv, config, error, fs, storm, util;

  argv = require('optimist').usage('Start stormflash agent with a configuration file.\nUsage: $0').demand('c')["default"]('c', '/etc/stormstack/stormflash.json').alias('c', 'config').describe('c', 'location of stormflash configuration file').argv;

  util = require('util');

  util.log("stormflash agent brewing up a new storm...");

  fs = require('fs');

  config = null;

  try {
    config = JSON.parse(fs.readFileSync(argv.config));
  } catch (_error) {
    error = _error;
    util.log(error);
    util.log("stormflash agent using default storm parameters...");
    config = {
      port: 8000,
      logfile: "/var/log/stormflash.log",
      datadir: "/var/stormflash",
      stormtracker: "auto",
      serialKey: "unknown",
      autobolt: true
    };
  } finally {
    util.log("stormflash agent infused with " + JSON.stringify(config));
  }

  fs = require('fs');

  try {
    if (!fs.existsSync("" + config.datadir)) {
      fs.mkdirSync("" + config.datadir);
    }
    if (!fs.existsSync("" + config.datadir + "/db")) {
      fs.mkdirSync("" + config.datadir + "/db");
    }
    if (!fs.existsSync("" + config.datadir + "/certs")) {
      fs.mkdirSync("" + config.datadir + "/certs");
    }
  } catch (_error) {
    error = _error;
    util.log("Error in creating data dirs");
  }

  storm = config.storm;

  storm = {
    provider: "openstack",
    tracker: "https://allow@stormtracker.dev.intercloud.net",
    skey: "some-secure-serial-key",
    id: "testing-uuid",
    cert: "",
    key: "",
    bolt: {
      remote: "bolt://bolt.dev.intercloud.net",
      listen: 123,
      local: 8017,
      local_forwarding_ports: [8000],
      beacon: {
        interval: 10,
        retry: 3
      }
    }
  };

  StormAgent = require('./stormagent');

  agent = new StormAgent(config);

  agent.on("ready", function() {
    this.log("loading API endpoints");
    this.include('./api');
    this.log("starting activation...");
    return this.activate(storm, (function(_this) {
      return function(err, status) {
        return _this.log("activation completed with ", JSON.stringify(status));
      };
    })(this));
  });

  agent.on("active", function(storm) {
    var bolt, stormbolt;
    this.log("firing up stormbolt...");
    stormbolt = require('stormbolt');
    bolt = new stormbolt(data);
    bolt.on("error", (function(_this) {
      return function(err) {
        _this.log("bolt error, force agent re-activation...");
        return _this.activate(config.storm, function(err, status) {
          return _this.log("re-activation completed with " + status);
        });
      };
    })(this));
    return bolt.start();
  });

  agent.run(function() {
    return agent.log("hello");
  });

}).call(this);
