// Generated by CoffeeScript 1.7.1
(function() {
  var client, options, request, stormflashurl;

  request = require('request-json');

  stormflashurl = 'http://localhost:5000';

  options = {
    timeout: 3000
  };

  client = request.newClient(stormflashurl, options);

  client.get("/status", (function(_this) {
    return function(err, res, body) {
      var pkg, pkgs, service, _i, _j, _len, _len1, _ref, _ref1, _ref10, _ref11, _ref12, _ref13, _ref14, _ref15, _ref16, _ref17, _ref18, _ref19, _ref2, _ref20, _ref21, _ref22, _ref23, _ref24, _ref25, _ref26, _ref27, _ref28, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9, _results;
      if (err != null) {
        console.log("err" + JSON.stringify(err));
      }
      if (err != null) {
        return null;
      }
      if (res.statusCode !== 200) {
        return null;
      }
      _this.status = body;
      if (((_ref = _this.status) != null ? _ref.id : void 0) != null) {
        console.log("uuid                      :  " + _this.status.id);
      }
      if (((_ref1 = _this.status) != null ? _ref1.activated : void 0) != null) {
        console.log("Activated                 :  " + _this.status.activated);
      }
      if (((_ref2 = _this.status) != null ? _ref2.running : void 0) != null) {
        console.log("Running                   :  " + _this.status.running);
      }
      if (((_ref3 = _this.status) != null ? (_ref4 = _ref3.os) != null ? _ref4.endianness : void 0 : void 0) != null) {
        console.log("endianness                :  " + _this.status.os.endianness);
      }
      if (((_ref5 = _this.status) != null ? (_ref6 = _ref5.os) != null ? _ref6.hostname : void 0 : void 0) != null) {
        console.log("hostname                  :  " + _this.status.os.hostname);
      }
      if (((_ref7 = _this.status) != null ? (_ref8 = _ref7.os) != null ? _ref8.platform : void 0 : void 0) != null) {
        console.log("platform                  :  " + _this.status.os.platform);
      }
      if (((_ref9 = _this.status) != null ? (_ref10 = _ref9.os) != null ? _ref10.release : void 0 : void 0) != null) {
        console.log("release                   :  " + _this.status.os.release);
      }
      if (((_ref11 = _this.status) != null ? (_ref12 = _ref11.os) != null ? _ref12.arch : void 0 : void 0) != null) {
        console.log("arch                      :  " + _this.status.os.arch);
      }
      if (((_ref13 = _this.status) != null ? (_ref14 = _ref13.os) != null ? _ref14.uptime : void 0 : void 0) != null) {
        console.log("uptime                    :  " + _this.status.os.uptime);
      }
      if (((_ref15 = _this.status) != null ? (_ref16 = _ref15.os) != null ? _ref16.loadavg : void 0 : void 0) != null) {
        console.log("loadavg                   :  " + _this.status.os.loadavg);
      }
      if (((_ref17 = _this.status) != null ? (_ref18 = _ref17.os) != null ? _ref18.totalmem : void 0 : void 0) != null) {
        console.log("totalmem                  :  " + _this.status.os.totalmem);
      }
      if (((_ref19 = _this.status) != null ? (_ref20 = _ref19.os) != null ? _ref20.freemem : void 0 : void 0) != null) {
        console.log("freemem                   :  " + _this.status.os.freemem);
      }
      console.log("Interfaces                :  ");
      if (((_ref21 = _this.status) != null ? (_ref22 = _ref21.os) != null ? (_ref23 = _ref22.networkInterfaces) != null ? (_ref24 = _ref23.wan0) != null ? (_ref25 = _ref24[0]) != null ? _ref25.address : void 0 : void 0 : void 0 : void 0 : void 0) != null) {
        console.log("wan0                      :  " + _this.status.os.networkInterfaces.wan0[0].address);
      }
      pkgs = "";
      _ref26 = _this.status.packages;
      for (_i = 0, _len = _ref26.length; _i < _len; _i++) {
        pkg = _ref26[_i];
        pkgs = pkgs + ", " + pkg.name;
      }
      if (pkgs != null) {
        console.log("packages installed        :  " + pkgs.slice(2));
      }
      console.log("Services                  :  ");
      _ref27 = _this.status.services;
      _results = [];
      for (_j = 0, _len1 = _ref27.length; _j < _len1; _j++) {
        service = _ref27[_j];
        if ((service != null ? (_ref28 = service.invocation) != null ? _ref28.name : void 0 : void 0) != null) {
          console.log("    Name                  :  " + service.invocation.name);
        }
        if ((service != null ? service.running : void 0) != null) {
          _results.push(console.log("    Running               :  " + service.running));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };
  })(this));

}).call(this);
